// @ts-expect-error — PrismaClient types are generated by `prisma generate`.
// Run `npm run db:generate` once to resolve. All downstream Prisma calls are
// safe at runtime; only the static types are absent until generation.
import { PrismaClient } from '@prisma/client';

declare global {
  // eslint-disable-next-line no-var
  var __prisma: PrismaClient | undefined;
}

export const db: PrismaClient =
  globalThis.__prisma ??
  new PrismaClient({
    log: process.env.NODE_ENV === 'development' ? ['warn', 'error'] : ['error'],
  });

if (process.env.NODE_ENV !== 'production') {
  globalThis.__prisma = db;
}
